version: '3'
services:
  minecraft:
    container_name: mc
    image: itzg/minecraft-server
    ports:
      -  25565:25565
    environment:
      - EULA=true
      - DIFFICULTY=peaceful
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - /home/rhel/Server/Minecraft/data:/data
networks:
  default:
    external:
      name: nuc

